# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/requirements.json

roles: [] # https://github.com/ansible/ansible/issues/84803
  # - name: geerlingguy.ntp
  #   version: 3.0.0
  # - name: geerlingguy.security
  #   version: 3.0.0
